## This file is generated by `update_install_R.R`, DO NOT EDIT BY HAND!!!

install.packages(c("remotes", "BiocManager"))
BiocManager::install()

BiocManager::install(c(
   "ExploreModelMatrix",
   "GGally",
   "NHANES",
   "Rmisc",
   "car",
   "coin",
   "dplyr",
   "faraway",
   "ggplot2",
   "gridExtra",
   "jsonlite",
   "kableExtra",
   "knitr",
   "limma",
   "multcomp",
   "plot3D",
   "plotrix",
   "readr",
   "rmarkdown",
   "sessioninfo",
   "tidyverse"
))
